---
title: "SWE salary analysis"
author: "Guochen Liao"
date: "2023-09-11"
output: html_document
---
Academic Honesty
Name(s) of all authors: Guochen
Assignment name: Individual Project
Assignment due date: TBD
Written/online sources used: None
Help obtained (Acknowledgments): None
Add the statement: We confirm that the above list of sources is complete AND that we have not talked to anyone else about the solution to this problem.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
library(qrcode)
library(lattice)
library(wordcloud2)
library(shiny)
library(leaflet)
library(maps)
library(sf)
library(shinydashboard)
```

```{r}
# Read the data from CSV file
salary_data <- read_csv("SweSalaries.csv")

# Separate city and state into two different columns
salary_data <- salary_data %>%
  separate(City, into = c("City_Name", "State_Name"), sep = ", ")

# Group data by state and calculate the average for the relevant columns
state_aggregated_data <- salary_data %>%
  group_by(State_Name) %>%
  summarise(
    Avg_MeanSalaryAdjusted = mean(MeanSalaryAdjusted, na.rm = TRUE),
    Avg_MeanSalary = mean(MeanSalary, na.rm = TRUE),
    Avg_HomePrice = mean(HomePrice, na.rm = TRUE),
    Avg_LivingCost = mean(LivingCost, na.rm = TRUE),
    Avg_Rent = mean(Rent, na.rm = TRUE),
    Avg_NumberJobs = mean(NumberJobs, na.rm = TRUE),
    Avg_PurPower = mean(PurPower, na.rm = TRUE)
  )

# Extract the top 10 states based on the average MeanSalaryAdjusted
top_10_states <- state_aggregated_data %>%
  arrange(desc(Avg_MeanSalaryAdjusted)) %>%
  head(10) 

# Plot the average MeanSalaryAdjusted for these top 10 states in a histogram
ggplot(top_10_states, aes(x = reorder(State_Name, Avg_MeanSalaryAdjusted), y = Avg_MeanSalaryAdjusted)) +
  geom_bar(stat = "identity", fill = "aquamarine", color = "black") +
  geom_bar(aes(y = Avg_MeanSalary), stat = "identity", fill = "orange", color = "black", alpha = 0.5) +
  xlab("State") +
  ylab("Average Mean Salaries") +
  ggtitle("Top 10 States by Average Mean Adjusted Salary")


```

```{r}
# Read the data from the CSV file
salary_data <- read_csv("SweSalaries.csv")

# Create a scatter plot with MeanSalary on the x-axis and HomePrice on the y-axis
ggplot(salary_data, aes(x = MeanSalary, y = HomePrice)) +
  geom_point() + 
  geom_smooth(method = "lm", col = "red") +
  xlab("Mean Salary") +
  ylab("HomePrice") +
  ggtitle("Scatterplot of HomePrice vs Mean Salary") 
```

```{r}
# Read the data from the CSV file
salary_data <- read_csv("SweSalaries.csv")

# Calculate the rent to mean salary adjusted ratio
salary_data <- salary_data %>% mutate(RentToSalaryRatio = (Rent * 12) / MeanSalaryAdjusted)

# Create a bubble plot
ggplot(salary_data, aes(x = MeanSalaryAdjusted, y = Rent, size = RentToSalaryRatio, colour = RentToSalaryRatio)) +
  geom_point(alpha = 0.6) +
  scale_size(range = c(1, 10)) +
  scale_colour_gradient(low = "blue", high = "red") +
  xlab("Mean Salary Adjusted") +
  ylab("Rent") +
  ggtitle("Bubble Plot of Rent vs Mean Salary Adjusted") 
```

```{R}
data <- read.csv("CombinedDataFile.csv")

# Read the shapefile
us_states <- st_read("cb_2018_us_state_20m/cb_2018_us_state_20m.shp")


# Join aggregated data with shapefile
us_states <- us_states %>%
  left_join(data, by = c("STUSPS" = "State"))


ui <- dashboardPage(
  dashboardHeader(title = "SWE Salary Analysis"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Map", tabName = "map", icon = icon("globe")),
      menuItem("Line Graph", tabName = "line_graph", icon = icon("line-chart"))
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(tabName = "map",
              fluidRow(
                column(width = 3,
                        selectInput("attribute", "Choose an attribute:", 
                        choices = colnames(data)[-1],
                        selected = colnames(data)[2]),
                        selectInput("presetFilter", "Choose a preset filter:", 
                        choices = c("No Filter", "High Salary", "Low Rent"), 
                        selected = "No Filter"),
                       numericInput("minSalaryAdjusted", "Min Mean SWE Salary:", min = 0, max = max(data$MeanSalaryAdjusted, na.rm = TRUE), value = 0),
                       numericInput("maxSalaryAdjusted", "Max Mean SWE Salary:", min = 0, max = max(data$MeanSalaryAdjusted, na.rm = TRUE), value = max(data$MeanSalaryAdjusted, na.rm = TRUE)),
                       numericInput("minRent", "Min Rent:", min = 0, max = max(data$Rent, na.rm = TRUE), value = 0),
                       numericInput("maxRent", "Max Rent:", min = 0, max = max(data$Rent, na.rm = TRUE), value = max(data$Rent, na.rm = TRUE)),
                       actionButton("applyFilter", "Filter")
                ),
                column(width = 9,
                       leafletOutput("map")
                )
              ),
              tableOutput("table")
      ),
      tabItem(tabName = "line_graph",
              fluidRow(
                column(width = 3,
                       selectInput("attribute1", "Select Attribute 1:", choices = colnames(data)[-1]),
                       selectInput("attribute2", "Select Attribute 2:", choices = colnames(data)[-1]),
                       actionButton("plotGraph", "Plot Graph")
                ),
                column(width = 9,
                       plotOutput("linePlot")
                )
              )
      )
    )
  )
)

# Transform the datum of us_states to +proj=longlat +datum=WGS84
us_states <- st_transform(us_states, 4326)


server <- function(input, output, session) {
    
  filtered_states <- reactiveVal(us_states) # Create a reactive value to store the filtered states
  
  observe({
    switch(input$presetFilter,
           "No Filter" = {
             updateNumericInput(session, "minSalaryAdjusted", value = 0)
             updateNumericInput(session, "maxSalaryAdjusted", value = max(data$MeanSalaryAdjusted, na.rm = TRUE))
             updateNumericInput(session, "minRent", value = 0)
             updateNumericInput(session, "maxRent", value = max(data$Rent, na.rm = TRUE))
           },
           "High Salary" = {
             updateNumericInput(session, "minSalaryAdjusted", value = 100000)
             updateNumericInput(session, "maxSalaryAdjusted", value = max(data$MeanSalaryAdjusted, na.rm = TRUE))
           },
           "Low Rent" = {
             updateNumericInput(session, "minRent", value = 0)
             updateNumericInput(session, "maxRent", value = 1000)
           },
           {
             updateNumericInput(session, "minSalaryAdjusted", value = 0)
             updateNumericInput(session, "maxSalaryAdjusted", value = max(data$MeanSalaryAdjusted, na.rm = TRUE))
             updateNumericInput(session, "minRent", value = 0)
             updateNumericInput(session, "maxRent", value = max(data$Rent, na.rm = TRUE))
           }
    )
  })
  
  observeEvent(input$applyFilter, {
    filtered_states(us_states) # Reset to original states when 'Filter' button is clicked
    
    # Apply filters based on input values
    if(!is.null(input$minSalaryAdjusted))
      filtered_states(filtered_states() %>% filter(MeanSalaryAdjusted >= input$minSalaryAdjusted))
    if(!is.null(input$maxSalaryAdjusted))
      filtered_states(filtered_states() %>% filter(MeanSalaryAdjusted <= input$maxSalaryAdjusted))
    if(!is.null(input$minRent))
      filtered_states(filtered_states() %>% filter(Rent >= input$minRent))
    if(!is.null(input$maxRent))
      filtered_states(filtered_states() %>% filter(Rent <= input$maxRent))
    # Add more filter conditions for other columns as needed
  })
  
  output$map <- renderLeaflet({
    # Define a color palette with a specified number of bins
    bins <- 10  # You can adjust this number as per your requirement
    pal <- colorBin(palette = "viridis", domain = filtered_states()[[input$attribute]], bins = bins)
    
    leaflet(data = filtered_states()) %>%
    addTiles() %>%
    fitBounds(-125, 24.396308, -66.934570, 49.384358) %>%
    addPolygons(fillColor = ~pal(filtered_states()[[input$attribute]]),
                color = "#BDBDC3", weight = 1,
                opacity = 1, fillOpacity = 0.7,
                highlight = highlightOptions(weight = 2,
                                             color = "#666",
                                             fillOpacity = 0.7,
                                             bringToFront = TRUE),
                popup = ~paste(
                  "<strong>State:</strong> ", STUSPS, "<br>",
                  "<strong>Mean Salary Adjusted:</strong> $", round(MeanSalaryAdjusted, 2), "<br>",
                  "<strong>Mean Salary Unadjusted:</strong> $", round(MeanSalaryUnadjusted, 2), "<br>",
                  "<strong>Mean Salary:</strong> $", round(MeanSalary, 2), "<br>",
                  "<strong>Number of Jobs:</strong> ", round(NumberJobs, 2), "<br>",
                  "<strong>Home Price:</strong> $", round(HomePrice, 2), "<br>",
                  "<strong>Living Cost:</strong> $", round(LivingCost, 2), "<br>",
                  "<strong>Rent:</strong> $", round(Rent, 2), "<br>",
                  "<strong>Plus Rent:</strong> $", round(PlusRent, 2), "<br>",
                  "<strong>Purchasing Power:</strong> ", round(PurPower, 2)
                ),
                group = "states")
  })

  
  output$linePlot <- renderPlot({
    input$plotGraph
    
    isolate({
      ggplot(data, aes_string(x = input$attribute1, y = input$attribute2)) +
        geom_point() + 
        geom_smooth(method = "lm", se = FALSE, color = "blue") +
        labs(y = input$attribute2, x = input$attribute1) +
        theme_minimal()
    })
  })
  
  
  
}


# Run the application
shinyApp(ui = ui, server = server)

```
